// Anatomical body map — renders the reference anatomy line art itself (public/body-front.png /
// body-back.png, light line art on a dark background) with a semi-transparent SVG shading overlay
// on top. Opacity per region = how much that muscle is worked.
//
// Region paths were traced against these exact images (front 482x973, back 470x966) in a fifth —
// and finally successful — calibration pass: full-image + zoomed-crop grid renders via `sharp` to
// read boundary coordinates off the drawn muscle outlines, then candidate paths composited back
// onto the real images and iterated until every region sat inside its muscle's contour (three
// iterations; earlier passes' persistent misses — e.g. the Quads region covering only the inner
// half of the thigh — came from never reading the outer-contour coordinates explicitly). Two
// structural changes over prior passes keep it right:
//   1. Only LEFT-side paths are stored; right side is generated by mirrorPath() around each
//      image's vertical centerline, so the two sides can never drift apart.
//   2. All of a muscle's subpaths render as ONE <path> element (concatenated `d`) — the Back
//      group's traps/lats/erector regions intentionally overlap, and separate semi-transparent
//      paths would double-darken where they cross; subpaths of a single path fill uniformly.
// If the reference images ever change, redo the same composite-and-check loop (throwaway scripts
// in a `.verify/` dir, viewed with the Read tool) rather than eyeballing coordinates.
const ACCENT_BASE = 'oklch(0.65 0.19 35';

const FRONT_W = 482, FRONT_H = 973;
const BACK_W = 470, BACK_H = 966;

// flips every x coordinate in an absolute M/L/Q path around the image's vertical centerline
function mirrorPath(d: string, width: number): string {
  return d.replace(/([MLQ])\s*([^MLQZ]+)/gi, (_m, cmd: string, coords: string) => {
    const nums = coords.trim().split(/[\s,]+/).map(Number);
    const out: string[] = [];
    for (let i = 0; i < nums.length; i += 2) out.push((width - nums[i]).toFixed(0) + ',' + nums[i + 1]);
    return cmd + out.join(' ');
  });
}

// left-side (and centered) region paths per muscle; `mirrored: true` adds the right-side copy
interface RegionDef { d: string; muscle: string; mirrored: boolean; }

const FRONT_DEFS: RegionDef[] = [
  { muscle: 'Shoulders', mirrored: true, d: 'M115,164 Q98,170 91,193 Q86,222 94,243 Q102,257 110,255 Q123,245 132,226 Q140,202 149,173 Q133,160 115,164 Z' },
  { muscle: 'Chest', mirrored: true, d: 'M235,176 Q192,168 156,172 Q136,204 139,234 Q147,262 176,272 Q212,277 235,271 Z' },
  { muscle: 'Biceps', mirrored: true, d: 'M94,253 Q109,264 115,275 Q118,310 112,344 Q105,372 95,383 Q84,376 78,350 Q74,317 81,285 Q86,260 94,253 Z' },
  { muscle: 'Core', mirrored: false, d: 'M173,277 Q241,286 309,277 Q317,330 307,380 Q288,436 241,458 Q194,436 175,380 Q165,330 173,277 Z' },
  { muscle: 'Quads', mirrored: true, d: 'M162,490 Q200,478 224,502 Q233,555 227,614 Q220,660 205,675 Q176,681 158,660 Q139,601 137,551 Q139,513 162,490 Z' },
  { muscle: 'Calves', mirrored: true, d: 'M181,704 Q209,699 227,714 Q233,754 226,794 Q216,824 200,831 Q184,820 177,779 Q172,739 181,704 Z' }
];

const BACK_DEFS: RegionDef[] = [
  { muscle: 'Rear Delts', mirrored: true, d: 'M124,161 Q104,169 97,193 Q92,223 100,245 Q108,258 117,256 Q130,246 139,226 Q147,200 154,172 Q138,157 124,161 Z' },
  // traps diamond + lat wings (raised medially to also cover the rhomboid/teres area) + erector
  // column — all one "Back" group, overlaps hidden by the single-path-per-muscle rendering.
  { muscle: 'Back', mirrored: false, d: 'M235,70 Q205,92 158,164 Q192,180 216,220 Q231,262 235,338 Q239,262 254,220 Q278,180 312,164 Q265,92 235,70 Z' },
  { muscle: 'Back', mirrored: true, d: 'M146,258 Q170,238 190,236 Q212,250 222,290 Q228,340 228,400 Q205,421 181,414 Q160,390 152,338 Q147,296 146,258 Z' },
  { muscle: 'Back', mirrored: false, d: 'M220,300 Q214,350 219,396 Q227,410 235,408 Q243,410 251,396 Q256,350 250,300 Q235,290 220,300 Z' },
  { muscle: 'Triceps', mirrored: true, d: 'M101,255 Q115,268 118,291 Q118,328 112,362 Q104,387 93,394 Q82,385 77,357 Q74,318 81,286 Q88,260 101,255 Z' },
  { muscle: 'Glutes', mirrored: true, d: 'M161,413 Q200,402 228,417 Q237,452 232,494 Q224,526 196,533 Q166,528 156,493 Q149,451 161,413 Z' },
  { muscle: 'Hamstrings', mirrored: true, d: 'M151,543 Q180,538 209,547 Q213,593 206,650 Q198,689 179,696 Q159,689 149,649 Q141,592 151,543 Z' },
  { muscle: 'Calves', mirrored: true, d: 'M141,700 Q166,691 186,704 Q196,741 190,780 Q182,813 164,821 Q145,812 137,774 Q132,734 141,700 Z' }
];

// one combined path per muscle: left + mirrored-right subpaths of every def for that muscle
function buildMusclePaths(defs: RegionDef[], width: number): { muscle: string; d: string }[] {
  const byMuscle: Record<string, string[]> = {};
  defs.forEach(def => {
    (byMuscle[def.muscle] = byMuscle[def.muscle] || []).push(def.d);
    if (def.mirrored) byMuscle[def.muscle].push(mirrorPath(def.d, width));
  });
  return Object.entries(byMuscle).map(([muscle, ds]) => ({ muscle, d: ds.join(' ') }));
}

const FRONT_PATHS = buildMusclePaths(FRONT_DEFS, FRONT_W);
const BACK_PATHS = buildMusclePaths(BACK_DEFS, BACK_W);

export function fillForMuscle(muscle: string | null, ranks: Record<string, number>): string {
  if (!muscle || !(muscle in ranks)) return 'transparent';
  const opacity = 0.28 + 0.6 * (ranks[muscle] || 0);
  return ACCENT_BASE + ' / ' + opacity.toFixed(2) + ')';
}

export function BodyDiagram({ view, ranks, width = 34, height = 63 }: {
  view: 'front' | 'back';
  ranks: Record<string, number>;
  width?: number;
  height?: number;
}) {
  const isFront = view === 'front';
  const src = `${import.meta.env.BASE_URL}${isFront ? 'body-front.png' : 'body-back.png'}`;
  const paths = isFront ? FRONT_PATHS : BACK_PATHS;
  const vbW = isFront ? FRONT_W : BACK_W;
  const vbH = isFront ? FRONT_H : BACK_H;
  return (
    <div style={{ width, height, position: 'relative', borderRadius: 8, overflow: 'hidden', background: '#0a0908', flex: 'none' }}>
      <img src={src} alt="" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'contain' }} />
      <svg viewBox={`0 0 ${vbW} ${vbH}`} preserveAspectRatio="xMidYMid meet" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}>
        {paths.map(p => <path key={p.muscle} d={p.d} fill={fillForMuscle(p.muscle, ranks)} />)}
      </svg>
    </div>
  );
}
