// Anatomical body map — renders the reference anatomy line art itself (public/body-front.png /
// body-back.png, light line art on a dark background) with a semi-transparent SVG shading overlay
// on top. Opacity per region = how much that muscle is worked.
//
// Region paths were traced against these exact images (front 482x973, back 470x966) across two
// full calibration passes (phase 21, then a phase-32 retrace of every arm and leg region plus new
// Forearms regions): full-image + zoomed-crop grid renders via `sharp` to read boundary
// coordinates off the drawn muscle outlines, then candidate paths composited back onto the real
// images and iterated until every region sat inside its muscle's contour. Keeping regions honest
// also means keeping them *apart*: adjacent muscles are separate semi-transparent paths, so any
// overlap (delt tip into biceps, lat tips onto glute tops) renders as a visibly darker band —
// the phase-32 iterations trimmed every such seam. Two structural choices keep all this right:
//   1. Only LEFT-side paths are stored; right side is generated by mirrorPath() around each
//      image's vertical centerline, so the two sides can never drift apart.
//   2. All of a muscle's subpaths render as ONE <path> element (concatenated `d`) — the Back
//      group's traps/lats/erector regions intentionally overlap, and separate semi-transparent
//      paths would double-darken where they cross; subpaths of a single path fill uniformly.
// If the reference images ever change, redo the same composite-and-check loop (throwaway scripts
// in a `.verify/` dir, viewed with the Read tool) rather than eyeballing coordinates.
const ACCENT_BASE = 'oklch(0.65 0.19 35';

const FRONT_W = 482, FRONT_H = 973;
const BACK_W = 470, BACK_H = 966;

// flips every x coordinate in an absolute M/L/Q path around the image's vertical centerline
function mirrorPath(d: string, width: number): string {
  return d.replace(/([MLQ])\s*([^MLQZ]+)/gi, (_m, cmd: string, coords: string) => {
    const nums = coords.trim().split(/[\s,]+/).map(Number);
    const out: string[] = [];
    for (let i = 0; i < nums.length; i += 2) out.push((width - nums[i]).toFixed(0) + ',' + nums[i + 1]);
    return cmd + out.join(' ');
  });
}

// left-side (and centered) region paths per muscle; `mirrored: true` adds the right-side copy
interface RegionDef { d: string; muscle: string; mirrored: boolean; }

const FRONT_DEFS: RegionDef[] = [
  { muscle: 'Shoulders', mirrored: true, d: 'M118,157 Q100,165 91,190 Q85,218 92,242 Q99,254 108,256 Q121,248 132,232 Q140,204 150,172 Q135,155 118,157 Z' },
  { muscle: 'Chest', mirrored: true, d: 'M235,176 Q192,168 156,172 Q136,204 139,234 Q147,262 176,272 Q212,277 235,271 Z' },
  // ends at the elbow crease (~y355 outer / ~y360 inner) — the crease is drawn as a diagonal, so
  // the bottom edge is one too; spilling past it was the "arms look off" the retrace fixed.
  { muscle: 'Biceps', mirrored: true, d: 'M102,252 Q119,255 124,274 Q128,306 120,338 Q114,354 104,360 Q93,352 88,330 Q84,296 90,264 Q95,253 102,252 Z' },
  { muscle: 'Forearms', mirrored: true, d: 'M63,357 Q94,349 98,362 Q91,406 76,440 Q66,461 56,467 Q46,460 44,437 Q49,392 63,357 Z' },
  { muscle: 'Core', mirrored: false, d: 'M173,277 Q241,286 309,277 Q317,330 307,380 Q288,436 241,458 Q194,436 175,380 Q165,330 173,277 Z' },
  // rises to y≈412 at the hip — the drawn rectus femoris/TFL notch — with the upper-inner edge
  // following the sartorius diagonal; the previous top at y≈490 left the whole upper quarter of
  // the drawn quad unshaded ("quads aren't going up high enough").
  { muscle: 'Quads', mirrored: true, d: 'M158,412 Q142,440 138,500 Q136,570 146,625 Q152,662 168,675 Q186,679 197,658 Q207,625 209,565 Q210,510 200,472 Q185,435 158,412 Z' },
  // the drawn lower-leg muscle mass (both visible bulges), ending above the ankle tendons — not
  // the old blob down the shin/achilles.
  { muscle: 'Calves', mirrored: true, d: 'M165,694 Q189,687 204,697 Q214,731 208,771 Q200,798 184,804 Q167,796 159,761 Q153,724 165,694 Z' }
];

const BACK_DEFS: RegionDef[] = [
  { muscle: 'Rear Delts', mirrored: true, d: 'M116,160 Q98,168 92,194 Q88,222 96,248 Q104,266 114,272 Q126,260 136,232 Q144,200 152,168 Q134,154 116,160 Z' },
  // traps diamond + lat wings (raised medially to also cover the rhomboid/teres area) + erector
  // column — all one "Back" group, overlaps hidden by the single-path-per-muscle rendering. Lat
  // bottom tips sit at y≈394-410 so they clear the glute domes below (separate muscles would
  // double-darken where they cross).
  { muscle: 'Back', mirrored: false, d: 'M235,70 Q205,92 158,164 Q192,180 216,220 Q231,262 235,338 Q239,262 254,220 Q278,180 312,164 Q265,92 235,70 Z' },
  { muscle: 'Back', mirrored: true, d: 'M146,258 Q170,238 190,236 Q212,250 222,290 Q228,340 227,394 Q204,410 182,403 Q159,384 152,338 Q147,296 146,258 Z' },
  { muscle: 'Back', mirrored: false, d: 'M220,300 Q214,350 219,396 Q227,410 235,408 Q243,410 251,396 Q256,350 250,300 Q235,290 220,300 Z' },
  { muscle: 'Triceps', mirrored: true, d: 'M103,264 Q122,272 126,295 Q126,324 116,346 Q106,359 95,362 Q81,353 76,328 Q74,300 84,275 Q93,262 103,264 Z' },
  { muscle: 'Forearms', mirrored: true, d: 'M57,358 Q87,350 93,364 Q88,410 74,443 Q63,465 52,470 Q42,463 40,440 Q44,396 57,358 Z' },
  // the drawn glute is a tilted egg, not a box: rounded dome top (below the lat tips), medial
  // edge stopping at x≈230 so the two sides leave the sacrum gap the art draws.
  { muscle: 'Glutes', mirrored: true, d: 'M183,414 Q161,420 154,458 Q151,502 165,528 Q182,542 202,536 Q220,528 227,499 Q230,462 221,432 Q206,410 183,414 Z' },
  // bellies end at y≈676 where the art splits into the two knee tendons — the old version tapered
  // to a point at y≈696, shading the back of the knee.
  { muscle: 'Hamstrings', mirrored: true, d: 'M150,546 Q172,536 200,545 Q209,578 206,622 Q200,664 178,676 Q156,664 146,626 Q140,584 150,546 Z' },
  { muscle: 'Calves', mirrored: true, d: 'M145,702 Q170,689 189,701 Q198,742 194,786 Q187,813 170,818 Q150,809 141,774 Q136,734 145,702 Z' }
];

// one combined path per muscle: left + mirrored-right subpaths of every def for that muscle
function buildMusclePaths(defs: RegionDef[], width: number): { muscle: string; d: string }[] {
  const byMuscle: Record<string, string[]> = {};
  defs.forEach(def => {
    (byMuscle[def.muscle] = byMuscle[def.muscle] || []).push(def.d);
    if (def.mirrored) byMuscle[def.muscle].push(mirrorPath(def.d, width));
  });
  return Object.entries(byMuscle).map(([muscle, ds]) => ({ muscle, d: ds.join(' ') }));
}

const FRONT_PATHS = buildMusclePaths(FRONT_DEFS, FRONT_W);
const BACK_PATHS = buildMusclePaths(BACK_DEFS, BACK_W);

export function fillForMuscle(muscle: string | null, ranks: Record<string, number>): string {
  if (!muscle || !(muscle in ranks)) return 'transparent';
  const opacity = 0.28 + 0.6 * (ranks[muscle] || 0);
  return ACCENT_BASE + ' / ' + opacity.toFixed(2) + ')';
}

export function BodyDiagram({ view, ranks, width = 34, height = 63 }: {
  view: 'front' | 'back';
  ranks: Record<string, number>;
  width?: number;
  height?: number;
}) {
  const isFront = view === 'front';
  const src = `${import.meta.env.BASE_URL}${isFront ? 'body-front.png' : 'body-back.png'}`;
  const paths = isFront ? FRONT_PATHS : BACK_PATHS;
  const vbW = isFront ? FRONT_W : BACK_W;
  const vbH = isFront ? FRONT_H : BACK_H;
  return (
    <div style={{ width, height, position: 'relative', borderRadius: 8, overflow: 'hidden', background: '#0a0908', flex: 'none' }}>
      <img src={src} alt="" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'contain' }} />
      <svg viewBox={`0 0 ${vbW} ${vbH}`} preserveAspectRatio="xMidYMid meet" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}>
        {paths.map(p => <path key={p.muscle} d={p.d} fill={fillForMuscle(p.muscle, ranks)} />)}
      </svg>
    </div>
  );
}
